import Header from '@/components/Header'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Suppermomos: Create event</title>
      </head>
      <body className="bg-gradient-main">
        <Header />
        {children}
      </body>
    </html>
  )
}
