import Header from '@/components/Header'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{
        background: "linear-gradient(138.11deg, #FEF452 0%, #942F70 121.92%)",
        minHeight: "100vh"
      }}>
        <Header />
        {children}
      </body>
    </html>
  )
}
